Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/RescueException:
  Exclude:
    - spec/**/*
