language: ruby
dist: trusty
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

after_script:
  - bundle exec codeclimate-test-reporter

env:
  CODECLIMATE_REPO_TOKEN: 085192d9e3537c39bd01d2f110619ba42dfc7899f5aaa883b612cf0cabdd65d4 
